### PR TITLE
Seungheonoh/liftyunlifty

### PR DESCRIPTION
**Pull request by SeungheonOh**
Attempt to make both lifty and unlifty available.

### CODE REVIEW

**Comment by SeungheonOh** [comment]
will replaces #37 once we are clear that there's no objection.

**Review by kozross — APPROVED** [review]

**Comment by peter-mlabs** [comment]
Is this good to merge?

**Comment by SeungheonOh** [comment]
No, not yet. I'll solve conflict and merge when ready. Thanks!

**Comment by emiflake** [comment]
This repository has been archived. This PR should be recreated in the [liqwid-libs](https://github.com/liqwid-Labs/liqwid-libs) repo if it's still important. Closing.

**Pull request closed without merging**
