### PR TITLE
PR comments on #26

### PR DESCRIPTION
**Pull request by peter-mlabs**
This PR addresses most of the comments on PR #26 that were related to formatting, comment grammar, kind signatures, etc. 

A few remaining comments are open that I'll try to address later today, but may need additional help with.

### CODE REVIEW

**Review by SeungheonOh — CHANGES_REQUESTED** [review]
I appreciate this a lot! I'm just wondering what is the difference between `{}` and `()` in kinds signatures. If they are the same, I'd default back to using `()` instead of curly braces.

~~It looks like Agda~~

**Comment by peter-mlabs** [comment]
>  If they are the same, I'd default back to using () instead of curly braces.

I don't think they are. When inside `newtype` declarations, `{}` doesn't work (with an error like "Inferred type variable not allowed in newtype declaration"), while `()` works fine.

**Comment by SeungheonOh** [comment]
Hmm. Than can we just use `()` for everything?

**Comment by peter-mlabs** [comment]
https://www.tweag.io/blog/2020-03-12-expl-spec/

Looks like the difference is that for `foo {a :: Type} (b :: Type)`, a call like `foo @bar` would set `b ~ bar`; things in curly braces are "skipped" for type applications.

**Comment by SeungheonOh** [comment]
Ah I see. Thanks for letting me know. I'll merge this to pq2 branch.

**Review by SeungheonOh — APPROVED** [review]

**Pull request merged**
