### PR TITLE
Exporting constraints that should've been exported.

### PR DESCRIPTION
**Pull request by SeungheonOh**

### CODE REVIEW

**Review by kozross — APPROVED** [review]
Not a fan of the type synonyms, but I'm not sure there's a better way.

**Comment by tbidne** [comment]
> Not a fan of the type synonyms, but I'm not sure there's a better way.

You could make some kind of class, but maybe the `boilerplate / gain` ratio isn't worth it.

```haskell
type NotPLam (p :: S -> Type) = IsLam (TestableTerm p) ~ 'False

-- or

class NotPLam p

instance IsLam (TesttableTerm p) ~ False => NotPLam p
```

**Comment by SeungheonOh** [comment]
Yeah, but that's basically same thing. I'm not sure if we want that over typesyn

**Comment by kozross** [comment]
I agree with @SeungheonOh here. It's far from an ideal situation, but Plutarch forces our hand.

**Pull request merged**
